import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

type DeviconSource = {
  name: string;
  altnames?: string[];
  tags?: string[];
  versions: { svg?: string[] };
  color?: string;
};

type TechDomain = 'application' | 'data' | 'tooling' | 'platform' | 'language' | 'design' | 'other';
type TechKind = 'framework' | 'library' | 'runtime' | 'datastore' | 'build-tool' | 'developer-tool' | 'cloud' | 'language' | 'design-tool' | 'other';
const ROOT = process.cwd();
const SOURCE_ROOT = join(ROOT, 'node_modules/devicon');
const ICON_OUTPUT = join(ROOT, 'public/devicons');
const CATALOG_OUTPUT = join(ROOT, 'src/generated/devicon-catalog.ts');

const BUILD_TOOLS = new Set(['babel', 'esbuild', 'gulp', 'grunt', 'parcel', 'postcss', 'rollup', 'rspack', 'swc', 'turbopack', 'vite', 'webpack']);

const hasAny = (tags: Set<string>, values: string[]) => values.some((value) => tags.has(value));

function classify(icon: DeviconSource): { domain: TechDomain; kind: TechKind } {
  const tags = new Set((icon.tags ?? []).map((tag) => tag.toLowerCase()));
  if (BUILD_TOOLS.has(icon.name)) return { domain: 'tooling', kind: 'build-tool' };
  if (hasAny(tags, ['database', 'db', 'sql', 'nosql', 'key-value', 'data'])) return { domain: 'data', kind: hasAny(tags, ['database', 'db']) ? 'datastore' : 'developer-tool' };
  if (hasAny(tags, ['cloud', 'hosting', 'paas', 'iaas', 'devops', 'container', 'orchestration', 'infrastructure'])) return { domain: 'platform', kind: 'cloud' };
  if (hasAny(tags, ['language', 'programming', 'compiler'])) return { domain: 'language', kind: 'language' };
  if (hasAny(tags, ['framework'])) return { domain: 'application', kind: 'framework' };
  if (hasAny(tags, ['library'])) return { domain: 'application', kind: 'library' };
  if (hasAny(tags, ['runtime'])) return { domain: 'application', kind: 'runtime' };
  if (hasAny(tags, ['design', 'graphics'])) return { domain: 'design', kind: 'design-tool' };
  if (hasAny(tags, ['tool', 'ide', 'editor', 'testing', 'package-manager', 'version-control'])) return { domain: 'tooling', kind: 'developer-tool' };
  return { domain: 'other', kind: 'other' };
}

async function selectVariant(icon: DeviconSource) {
  const variants = icon.versions.svg ?? [];
  const preferences = ['original', 'plain', 'line', 'original-wordmark', 'plain-wordmark', 'line-wordmark'];
  for (const variant of [...preferences, ...variants]) {
    if (!variants.includes(variant)) continue;
    const source = join(SOURCE_ROOT, 'icons', icon.name, `${icon.name}-${variant}.svg`);
    if (await Bun.file(source).exists()) return { variant, source };
  }
  return null;
}

async function main() {
  const source = await Bun.file(join(SOURCE_ROOT, 'devicon.json')).json() as DeviconSource[];
  const deviconPackage = await Bun.file(join(SOURCE_ROOT, 'package.json')).json() as { version: string };
  await mkdir(ICON_OUTPUT, { recursive: true });
  await mkdir(join(ROOT, 'src/generated'), { recursive: true });

  const catalog = [];
  for (const icon of source) {
    const selected = await selectVariant(icon);
    if (!selected) continue;
    const filename = `${icon.name}.svg`;
    await copyFile(selected.source, join(ICON_OUTPUT, filename));
    catalog.push({
      id: icon.name,
      name: icon.name,
      aliases: icon.altnames ?? [],
      tags: icon.tags ?? [],
      ...classify(icon),
      color: icon.color ?? null,
      iconVariant: selected.variant,
      iconUrl: `/devicons/${filename}`,
    });
  }

  catalog.sort((a, b) => a.id.localeCompare(b.id));
  const output = `/* This file is generated by bun run sync:devicons. Do not edit manually. */\n\n` +
    `export type TechDomain = 'application' | 'data' | 'tooling' | 'platform' | 'language' | 'design' | 'other';\n` +
    `export type TechKind = 'framework' | 'library' | 'runtime' | 'datastore' | 'build-tool' | 'developer-tool' | 'cloud' | 'language' | 'design-tool' | 'other';\n` +
    `export const DEVICON_VERSION = ${JSON.stringify(deviconPackage.version)};\n\n` +
    `export type DeviconTech = {\n  id: string;\n  name: string;\n  aliases: string[];\n  tags: string[];\n  domain: TechDomain;\n  kind: TechKind;\n  color: string | null;\n  iconVariant: string;\n  iconUrl: string;\n};\n\n` +
    `export const DEVICON_CATALOG: DeviconTech[] = ${JSON.stringify(catalog, null, 2)};\n\n` +
    `export const DEVICONS_BY_DOMAIN = Object.groupBy(DEVICON_CATALOG, ({ domain }) => domain) as Partial<Record<TechDomain, DeviconTech[]>>;\n`;
  await writeFile(CATALOG_OUTPUT, output);

  const counts = Object.fromEntries(Object.entries(Object.groupBy(catalog, ({ domain }) => domain)).map(([domain, icons]) => [domain, icons?.length ?? 0]));
  console.log(`Synced ${catalog.length} Devicon SVGs.`);
  console.log(counts);
}

await main();
