import { copyFile, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

type DeviconSource = {
  name: string;
  altnames?: string[];
  tags?: string[];
  versions: { svg?: string[] };
  color?: string;
};

type TechDomain = 'application' | 'data' | 'tooling' | 'platform' | 'language' | 'design' | 'other';
type TechKind = 'framework' | 'library' | 'runtime' | 'datastore' | 'build-tool' | 'developer-tool' | 'cloud' | 'language' | 'design-tool' | 'other';
type Reel = 'frontend' | 'backend' | 'database' | null;

const ROOT = process.cwd();
const SOURCE_ROOT = join(ROOT, 'node_modules/devicon');
const ICON_OUTPUT = join(ROOT, 'public/devicons');
const CATALOG_OUTPUT = join(ROOT, 'src/generated/devicon-catalog.ts');

const FRONTEND_REEL = new Set(['alpinejs', 'angular', 'angularjs', 'astro', 'blazor', 'htmx', 'jquery', 'mithril', 'nextjs', 'nuxtjs', 'pixijs', 'pyscript', 'react', 'solidjs', 'stenciljs', 'svelte', 'threejs', 'vuejs']);
const BACKEND_REEL = new Set(['adonisjs', 'bun', 'denojs', 'django', 'dotnetcore', 'express', 'fastapi', 'flask', 'laravel', 'nestjs', 'nodejs', 'phoenix', 'rails', 'spring', 'symfony']);
const DATABASE_REEL = new Set(['aerospike', 'azuresqldatabase', 'cassandra', 'clickhouse', 'cosmosdb', 'couchbase', 'couchdb', 'duckdb', 'dynamodb', 'faunadb', 'firebase', 'firebird', 'influxdb', 'mariadb', 'memcached', 'microsoftsqlserver', 'mongodb', 'mysql', 'neo4j', 'oracle', 'postgresql', 'realm', 'redis', 'rocksdb', 'spicedb', 'sqlite', 'supabase', 'surrealdb', 'vitess', 'yugabytedb']);
const BUILD_TOOLS = new Set(['babel', 'esbuild', 'gulp', 'grunt', 'parcel', 'postcss', 'rollup', 'rspack', 'swc', 'turbopack', 'vite', 'webpack']);

const hasAny = (tags: Set<string>, values: string[]) => values.some((value) => tags.has(value));

function classify(icon: DeviconSource): { domain: TechDomain; kind: TechKind; reel: Reel } {
  if (FRONTEND_REEL.has(icon.name)) return { domain: 'application', kind: icon.name === 'jquery' ? 'library' : 'framework', reel: 'frontend' };
  if (BACKEND_REEL.has(icon.name)) return { domain: 'application', kind: ['bun', 'denojs', 'dotnetcore', 'nodejs'].includes(icon.name) ? 'runtime' : 'framework', reel: 'backend' };
  if (DATABASE_REEL.has(icon.name)) return { domain: 'data', kind: 'datastore', reel: 'database' };
  if (BUILD_TOOLS.has(icon.name)) return { domain: 'tooling', kind: 'build-tool', reel: null };
  const tags = new Set((icon.tags ?? []).map((tag) => tag.toLowerCase()));
  if (hasAny(tags, ['database', 'db', 'sql', 'nosql', 'key-value', 'data'])) return { domain: 'data', kind: 'developer-tool', reel: null };
  if (hasAny(tags, ['cloud', 'hosting', 'paas', 'iaas', 'devops', 'container', 'orchestration', 'infrastructure'])) return { domain: 'platform', kind: 'cloud', reel: null };
  if (hasAny(tags, ['language', 'programming', 'compiler'])) return { domain: 'language', kind: 'language', reel: null };
  if (hasAny(tags, ['design', 'graphics'])) return { domain: 'design', kind: 'design-tool', reel: null };
  if (hasAny(tags, ['tool', 'ide', 'editor', 'testing', 'package-manager', 'version-control'])) return { domain: 'tooling', kind: 'developer-tool', reel: null };
  return { domain: 'other', kind: 'other', reel: null };
}

async function selectVariant(icon: DeviconSource) {
  const variants = icon.versions.svg ?? [];
  const preferences = ['original', 'plain', 'line', 'original-wordmark', 'plain-wordmark', 'line-wordmark'];
  for (const variant of [...preferences, ...variants]) {
    if (!variants.includes(variant)) continue;
    const source = join(SOURCE_ROOT, 'icons', icon.name, `${icon.name}-${variant}.svg`);
    if (await Bun.file(source).exists()) return { variant, source };
  }
  return null;
}

async function main() {
  const source = await Bun.file(join(SOURCE_ROOT, 'devicon.json')).json() as DeviconSource[];
  await mkdir(ICON_OUTPUT, { recursive: true });
  await mkdir(join(ROOT, 'src/generated'), { recursive: true });

  const catalog = [];
  for (const icon of source) {
    const selected = await selectVariant(icon);
    if (!selected) continue;
    const filename = `${icon.name}.svg`;
    await copyFile(selected.source, join(ICON_OUTPUT, filename));
    catalog.push({
      id: icon.name,
      name: icon.name,
      aliases: icon.altnames ?? [],
      tags: icon.tags ?? [],
      ...classify(icon),
      color: icon.color ?? null,
      iconVariant: selected.variant,
      iconUrl: `/devicons/${filename}`,
    });
  }

  catalog.sort((a, b) => a.id.localeCompare(b.id));
  const output = `/* This file is generated by bun run sync:devicons. Do not edit manually. */\n\n` +
    `export type TechDomain = 'application' | 'data' | 'tooling' | 'platform' | 'language' | 'design' | 'other';\n` +
    `export type TechKind = 'framework' | 'library' | 'runtime' | 'datastore' | 'build-tool' | 'developer-tool' | 'cloud' | 'language' | 'design-tool' | 'other';\n` +
    `export type DeviconReel = 'frontend' | 'backend' | 'database' | null;\n\n` +
    `export type DeviconTech = {\n  id: string;\n  name: string;\n  aliases: string[];\n  tags: string[];\n  domain: TechDomain;\n  kind: TechKind;\n  reel: DeviconReel;\n  color: string | null;\n  iconVariant: string;\n  iconUrl: string;\n};\n\n` +
    `export const DEVICON_CATALOG: DeviconTech[] = ${JSON.stringify(catalog, null, 2)};\n\n` +
    `export const DEVICONS_BY_DOMAIN = Object.groupBy(DEVICON_CATALOG, ({ domain }) => domain) as Partial<Record<TechDomain, DeviconTech[]>>;\n` +
    `export const DEVICONS_BY_REEL = Object.groupBy(DEVICON_CATALOG.filter(({ reel }) => reel), ({ reel }) => reel as Exclude<DeviconReel, null>) as Partial<Record<Exclude<DeviconReel, null>, DeviconTech[]>>;\n`;
  await writeFile(CATALOG_OUTPUT, output);

  const counts = Object.fromEntries(Object.entries(Object.groupBy(catalog, ({ domain }) => domain)).map(([domain, icons]) => [domain, icons?.length ?? 0]));
  console.log(`Synced ${catalog.length} Devicon SVGs.`);
  console.log(counts);
}

await main();
